services:
  postgres_service:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_USER: your_username
      POSTGRES_DB: your_database_name
    ports:
      - 5432:5432
    volumes:
      postgres_data:/var/lib/postgresql/data/pgdata
volumes:
  postgres_data: